In [1]:
import sys
print(sys.executable)

c:\Users\dell\Desktop\GenAI_Course\venv311\Scripts\python.exe

In [2]:
import tensorflow as tf
import keras

print("TensorFlow:", tf.__version__)
print("Keras:", keras.__version__)

WARNING:tensorflow:From c:\Users\dell\Desktop\GenAI_Course\venv311\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

TensorFlow: 2.15.0
Keras: 2.15.0

In [3]:
import tensorflow as tf 
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [4]:
##Load the trained model, scale pickle, onehot encoders
model = load_model('model.h5', compile=False)

#Load the encoder and scale
with open('onehot_encoder_geo.pkl','rb') as file:
    lable_encoder_geo = pickle.load(file)

with open('label_encoder_gender.pkl','rb') as file:
    lable_encoder_gender = pickle.load(file)

with open('scale.pkl','rb') as file:
    scaler = pickle.load(file)

WARNING:tensorflow:From c:\Users\dell\Desktop\GenAI_Course\venv311\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

c:\Users\dell\Desktop\GenAI_Course\venv311\Lib\site-packages\sklearn\base.py:525: InconsistentVersionWarning: Trying to unpickle estimator OneHotEncoder from version 1.5.0 when using version 1.9.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [5]:
input_data = {
    'CreditScore': 600,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

In [9]:
##One hot encode geography
geo_encoded = lable_encoder_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded,columns =lable_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

c:\Users\dell\Desktop\GenAI_Course\venv311\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [7]:
input_df = pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [8]:
input_df['Gender'] = lable_encoder_gender.transform([input_data['Gender']])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [13]:
input_df.columns

Index(['CreditScore', 'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts',
       'HasCrCard', 'IsActiveMember', 'EstimatedSalary', 'Geography_France',
       'Geography_Germany', 'Geography_Spain'],
      dtype='str')

In [14]:
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [15]:
input_scale = scaler.transform(input_df)
input_scale

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [16]:
prediction = model.predict(input_scale)
prediction

1/1 [==============================] - 0s 433ms/step

array([[0.02192422]], dtype=float32)

In [18]:
prediction_proba = prediction[0][0]
prediction_proba

0.021924222